= JAX-RS &amp; Messaging

This examples uses JAX-RS resource implementations and deploys
them through a user-provided `main()` programatically without
construction a `.war` file during the build.

Additionally, it configures a JMS server and sets up some
JMS destinations for use by the JAX-RS resource.

It also deploys an MSC service to consume messages from
the destination. 

> Please raise any issues found with this example in our JIRA:
> https://issues.jboss.org/browse/SWARM[https://issues.jboss.org/browse/SWARM]

== Project `pom.xml`

The project is a normal maven project with `jar` packaging, not `war`.

[source,xml]
----
<packaging>jar</packaging>
----

The project adds a `&lt;plugin&gt;` to configure `wildfly-swarm-plugin` to
create the runnable `.jar`.

[source,xml]
----
<plugin>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>wildfly-swarm-plugin</artifactId>
  <version>${version.wildfly-swarm}</version>
  <configuration>
    <mainClass>org.wildfly.swarm.examples.messaging.Main</mainClass>
  </configuration>
  <executions>
    <execution>
      <goals>
        <goal>package</goal>
      </goals>
    </execution>
  </executions>
</plugin>
----

To define the needed parts of WildFly Swarm, some dependencies are added

[source,xml]
----
<dependency>
    <groupId>org.wildfly.swarm</groupId>
    <artifactId>jaxrs</artifactId>
    <version>${version.wildfly-swarm}</version>
</dependency>
<dependency>
    <groupId>org.wildfly.swarm</groupId>
    <artifactId>messaging</artifactId>
    <version>${version.wildfly-swarm}</version>
</dependency>
<dependency>
    <groupId>org.wildfly.swarm</groupId>
    <artifactId>msc</artifactId>
    <version>${version.wildfly-swarm}</version>
</dependency>
----

== Project `main()`

This project supplies a `main()` in order to configure the messaging
subsystem and deploy all the pieces of the application.

[source,java]
----
include::src/main/java/org/wildfly/swarm/examples/messaging/Main.java[lines=15..40]
----

See: link:src/main/java/org/wildfly/swarm/examples/messaging/Main.java#L15[Main.java]

After the container is instantiated, the Messaging fraction is
configured and installed, enabling the in-vm connector and setting
up a topic and a queue. 

The container is started.

A JAX-RS deployment based on a project class is deployed, as is the
MSC service-activator, which activates a service to consume messages.

You can run it many ways:

* mvn package &amp;&amp; java -jar ./target/example-messaging-swarm.jar
* mvn wildfly-swarm:run

== Use

[source]
----
http://localhost:8080/
----

On the console the MSC service will print the message it received over JMS

[source]
----
2015-05-04 14:05:11,457 INFO [stdout] (Thread-2 (HornetQ-client-global-threads-316630753)) received: Hello!
----
