= WildFly-Swarm Examples

> Please raise any issues found with the examples in our JIRA:
> https://issues.jboss.org/browse/SWARM

== Thorntail

This repository contains examples for the http://wildfly-swarm.io[Thorntail] project.

It is currently listed as *alpha* release software, subject to massive, possibly-breaking,
changes as we determine exactly how it should all hang together.

== These Examples

These examples demonstrate utilizing and combining different parts of WildFly to create
a self-contained executable jar. They provide small, specific, working examples that can be used
as a reference for your own project.

By default, this repository uses `SNAPSHOT` versions of Thorntail.  They are used to test
particular aspects of the Thorntail project in addition to being useful examples of what
you can do and how you can do it.

Since these examples are `SNAPSHOT`-centric, our *snapshot* repository is added to the
root `pom.xml`.  If you were to build https://github.com/thorntail/thorntail[Thorntail]
directly, that would of course take precedence.

If you want to build these examples as they stand (using the snapshot) then you should start by either
running mvn install (use -DskipTests if you only want to run a specific test(s) at a time) or
mvn install inside base/ first and then you can build each individually.

If you want to use our *snapshot* repository in your own projects, include this in your `pom.xml`:

[source,xml]
----
<repositories>
  <repository>
    <id>projectodd-snapshots</id>
    <name>Project:odd Snapshots from CI</name>
    <url>https://repository-projectodd.forge.cloudbees.com/snapshot</url>
    <releases>
      <enabled>false</enabled>
    </releases>
    <snapshots>
      <enabled>true</enabled>
    </snapshots>
  </repository>
</repositories>
<pluginRepositories>
  <pluginRepository>
    <id>projectodd-snapshots</id>
    <name>Project:odd Snapshots from CI</name>
    <url>https://repository-projectodd.forge.cloudbees.com/snapshot</url>
    <releases>
      <enabled>false</enabled>
    </releases>
    <snapshots>
        <enabled>true</enabled>
    </snapshots>
  </pluginRepository>
</pluginRepositories>
----

To run the examples for a given release, please clone and checkout the particular Git tag
or https://github.com/wildfly-swarm/wildfly-swarm-examples/releases[download from the releases].

== UberJar vs non

By default, each example runs using the Maven plugin without constructing
an *uberjar*.  To run them as an *uberjar*, use the `-Puberjar` profile
when invoking Maven.

    mvn install -Puberjar

== Docker

We have some examples that use Docker which are located in /docker. Building the examples requires that Docker is installed
on your machine and that you run Maven with:

    mvn install -Pdocker
