= XML Configuration

This example demonstrates how to use XML configuration instead of the java config-api,
to configure WildFly Swarm. This might be useful, when you are migrating from a traditional
WildFly deployment and you have your `standalone.xml` file ready.

To build this example, execute `mvn package` on the command line in the directory where
this README is located.

== Referencing standalone.xml

To supply a `standalone.xml` you have three choices:

1. Reference an explict path using `-c` command line parameter:

[source,sh]
----
cd xml-configuration
java -jar target/example-xml-config-swarm.jar -c ../standalone.xml
----

2. Place your `standalone.xml` in the directory from which you are starting the WildFly Swarm
executable jar:

[source,sh,subs="quotes"]
----
cd xml-configuration/..
ls
cdi-injection  pom.xml  *standalone.xml*  xml-configuration
java -jar xml-configuration/target/example-xml-config-swarm.jar
----

3. Package your `standalone.xml` in the root directory of your WildFly Swarm
executable jar:

[source,sh]
----
cd xml-configuration
cp -t src/main/resources ../standalone.xml
mvn clean package
java -jar target/example-xml-config-swarm.jar
----


== Subsystem configuration in XML

You can then have any subsystem configuration external in `standalone.xml`.
These configuration will then be matched with the corresponding fractions automatically.

In in our example link:../standalone.xml#L130-L147[standalone.xml#L130-L147] file, we configure a custom datasource
called `CustomDS`:

[source,xml]
----
include::../standalone.xml[lines=130..147]
----

To prove that the configuration works, we use the `CustomDS` datasource in a JAX-RS endpoint
link:src/main/java/org/wildfly/swarm/examples/config/xml/MyResource.java#L24[MyResource#L24].

Note that the XML configuration file depicts just the runtime configuration and therefore,
you still need to ensure at build time (via dependencies in link:pom.xml#L70-L73[pom.xml]) that all necessary
fractions get packaged. Otherwise, you may get warnings and/or errors during the boot.
