= JAX-RS Health Endpoints

See also the userguide section for monitoring and security realms:
https://wildfly-swarm.gitbooks.io/wildfly-swarm-users-guide/content/advanced/monitoring.html

This example uses the `monitor` and `management` fractions
so that the JAX-RS endpoints can securely expose health checks to service registries.

> Please raise any issues found with this example in our JIRA:
> https://issues.jboss.org/browse/SWARM

== Project `pom.xml`
----

The project adds a `<plugin>` to configure `wildfly-swarm-plugin` to
create the runnable `.jar`.

[source,xml]
----
<plugin>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>wildfly-swarm-plugin</artifactId>
  <version>${version.wildfly-swarm}</version>
  <executions>
    <execution>
      <goals>
        <goal>package</goal>
      </goals>
    </execution>
  </executions>
</plugin>
----

To define the needed parts of WildFly Swarm, dependencies are added

[source,xml]
----
<dependency>
    <groupId>org.wildfly.swarm</groupId>
    <artifactId>jaxrs</artifactId>
    <version>${version.wildfly-swarm}</version>
</dependency>

<dependency>
       <groupId>org.wildfly.swarm</groupId>
       <artifactId>monitor</artifactId>
       <version>${version.wildfly-swarm}</version>
</dependency>
----

== @Health Annotations

In our example, we annotate the JAX-RS resource to be exposed as a health endpoint:

[source,java]
----
include::src/main/java/org/wildfly/swarm/examples/jaxrs/health/HealthCheckResource.java[lines=14..22]
----

See: link:src/main/java/org/wildfly/swarm/examples/jaxrs/health/HealthCheckResource.java#L14[HealthCheckResource.java]

By pointing your browser at http://localhost:8080/health and be able to retrieve the health response.

== Run

You can run it many ways:

* mvn package && java -jar ./target/example-jaxrs-health-swarm.jar
* mvn wildfly-swarm:run
* In your IDE run the `org.wildfly.swarm.examples.jaxrs.health.Main` class

== Use

To `GET` the health response

    http://localhost:8080/health

