= JAX-RS & ShrinkWrap Example

This examples uses JAX-RS resource implementations and deploys
them through a user-provided `main()` programatically without
construction a `.war` file during the build.

> Please raise any issues found with this example in our JIRA:
> https://issues.jboss.org/browse/SWARM

== Project `pom.xml`

The project is a normal maven project with `jar` packaging, not `war`.

[source,xml]
----
<packaging>jar</packaging>
----

The project adds a `<plugin>` to configure `wildfly-swarm-plugin` to
create the runnable `.jar`.

[source,xml]
----
<plugin>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>wildfly-swarm-plugin</artifactId>
  <version>${version.wildfly-swarm}</version>
  <configuration>
    <mainClass>org.wildfly.swarm.examples.jaxrs.shrinkwrap.Main</mainClass>
  </configuration>
  <executions>
    <execution>
      <goals>
        <goal>package</goal>
      </goals>
    </execution>
  </executions>
</plugin>
----

To define the needed parts of WildFly Swarm, a dependency is added

[source,xml]
----
<dependency>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>jaxrs</artifactId>
  <version>${version.wildfly-swarm}</version>
</dependency>
----

This dependency allows usage of ShrinkWrap APIs within the `main()` in addition
to providing the JAX-RS APIs.

== Project `main()`

Since this project deploys JAX-RS resources without a `.war` being construction, it
provides its own `main()` method (specified above via the `wildfly-swarm-plugin`) to
configure the container and deploy the resources programatically.

[source,java]
----
include::src/main/java/org/wildfly/swarm/examples/jaxrs/shrinkwrap/Main.java[lines=13..23]
----

This method constructs a new default Swarm container, which automatically
initializes all fractions (or subsystems) that are available.

A `JAXRSArchive` is constructed, and the JAX-RS resource class is
added to it.

The container is then started with the deployment.

By default, if no JAX-RS `Application` is provided a default is added
to the deployment specifying an `@ApplicationPath("/")` to bind the
deployment to the root URL.

We could modify the above `main()` method with:

[source,java]
----
deployment.addClass(MyApp.class);
----

to provide our own JAX-RS `Application`, which would modify the path to be
`http://localhost:8080/taco`.

== Run

You can run it many ways:

* mvn package && java -jar ./target/example-jaxrs-shrinkwrap-swarm.jar
* mvn wildfly-swarm:run
* In your IDE run the `org.wildfly.swarm.examples.jaxrs.shrinkwrap.Main` class

== Use

    http://localhost:8080/
