= JAX-RS &amp; Messaging MDB

This examples takes a normal JAX-RS and MDB build, and wraps it into a `-swarm` runnable jar.

Additionally, it configures a JMS server, sets up some
JMS destinations for use by the JAX-RS resource and
deploys an MDB to consume messages from the destination.

> Please raise any issues found with this example in our JIRA:
> https://issues.jboss.org/browse/SWARM[https://issues.jboss.org/browse/SWARM]

== Project `pom.xml`

The project is a normal maven project with  packaging of `war` in the pom.xml.

[source,xml]
----
<packaging>war</packaging>
----

The project adds a `plugin` to configure `wildfly-swarm-plugin` to
create the runnable `.jar`.

[source,xml]
----
<plugin>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>wildfly-swarm-plugin</artifactId>
  <executions>
    <execution>
      <id>package</id>
    </execution>
    <execution>
      <id>start</id>
    </execution>
    <execution>
      <id>stop</id>
    </execution>
  </executions>
</plugin>
----

To define the required parts of Thorntail, some dependencies are added

[source,xml]
----
<dependency>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>jaxrs</artifactId>
</dependency>
<dependency>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>cdi</artifactId>
</dependency>
<dependency>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>messaging</artifactId>
</dependency>
<dependency>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>ejb</artifactId>
</dependency>
----

== Run


You can run it many ways:

* mvn package &amp;&amp; java -jar ./target/example-messaging-mdb-swarm.jar
* mvn wildfly-swarm:run
* In your IDE run the `org.wildfly.swarm.Swarm` class

== Use

To access the JAX-RS Resource:

[source]
----
http://localhost:8080/
----

The JAX-RS endpoint publishes a message to JMS and returns:
----
Howdy!
----

On the console the MDB will print the message it received over JMS

[source,sh]
----
2015-10-08 05:05:43,432 ERROR [stderr] (Thread-1 (ActiveMQ-client-global-threads-682848512)) received: Hello!
----