= Datasource via Fraction

> Please raise any issues found with this example in our JIRA:
> https://issues.jboss.org/browse/SWARM

This example demonstrates how to create a datasource through
fraction configuration.

Deploying a JDBC driver through this method requires that
the driver be a part of the JBoss Modules module tree. 

Just as WildFly-Swarm can provide portions of the module tree
through various jars, so can your own application.

By creating `src/main/resources/modules/com/h2database/h2/main/module.xml`,
this new module is made available during the boot of the app-server.

The `module.xml` references the `h2.jar` through Maven coordinates and
property substitution:

[source,xml]
----
<resources>
  <artifact name="com.h2database:h2:${version.h2}"/>
</resources>
----

The `${version.h2}` is simply a property defined in your `pom.xml`,
and normal Maven resource-filtering replaces it, to avoid having
to hard-code it.

== Project `pom.xml`

The project is a normal maven project with `jar` packaging, not `war`.

[source,xml]
----
<packaging>jar</packaging>
----

The project adds a `<plugin>` to configure `wildfly-swarm-plugin` to
create the runnable `.jar`.  Additional configuration parameters are
added to instruct the plugin to include the `com.h2database.h2` module
from the WildFly distribution.  This allows access to the H2 driver
jar.

[source,xml]
----
<plugin>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>wildfly-swarm-plugin</artifactId>
  <configuration>
    <mainClass>org.wildfly.swarm.examples.ds.subsystem.Main</mainClass>
  </configuration>
  ....
</plugin>
----
    
As with the other examples, this one inherits a few standard executions
from the parent `pom.xml`, particularly the `package` execution.
    
To define the needed parts of WildFly Swarm, a few dependencies are added.
The first is not strictly required for configuring datasources, but is
needed for the example to demonstrate usage of the datasource:

[source,xml]
----
<dependency>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>jaxrs</artifactId>
</dependency>
----
    
To support datasources in general, the next dependency is required:
    
[source,xml]
----
<dependency>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>datasources</artifactId>
</dependency>
----

The `jaxrs` dependency allows usage of ShrinkWrap APIs within the `main()` in addition
to providing the JAX-RS APIs.  The `datasources` dependency provides configuration
classes for adding the JDBC driver and datasources to the container.

== Project `main()`

Since this project deploys JAX-RS resources without a `.war` being construction, it
provides its own `main()` method (specified above via the `maven-jar-plugin`) to
configure the container and deploy the resources programatically.


[source,java]
----
include::src/main/java/org/wildfly/swarm/examples/ds/subsystem/Main.java[lines=11..95]
----

This method constructs a new default Swarm, which automatically
initializes all fractions (or subsystems) that are available.  The datasources
fraction has no particular default configuration, so by providing a
specific configuration we enable a driver and a datasource.

JNDI names are bound automatically.

The empty container is started.

A `JAXRSDeployment` is constructed, and the JAX-RS resource class is
added to it and then deployed to the container.

The resource looks up the Datasource through JNDI at run-time:


[source,java]
----
include::src/main/java/org/wildfly/swarm/examples/ds/subsystem/MyResource.java[lines=17..32]
----


== Run

You can run it many ways:

* mvn package && java -jar ./target/example-datasource-subsystem-swarm.jar
* mvn wildfly-swarm:run
* In your IDE run the `org.wildfly.swarm.examples.ds.subsystem.Main` class

== Use

    http://localhost:8080/

== (Option) Other Database usage

Of course, you can also use other databases such as PostgreSQL.

When you want to use PostgreSQL JDBC Driver and datasource,
simply set the `swarm.use.db` system property to a value of `postgresql`.

