= JAX-RS & Swagger Example

This example builds on the "jaxrs" example by adding the `swagger` fraction
so that the JAX-RS API is exposed through the /swagger.json
URL.

> Please raise any issues found with this example in our JIRA:
> https://issues.jboss.org/browse/THORN

== Project `pom.xml`

The project is a normal maven project with `jar` packaging, not `war`.

[source,xml]
----
<packaging>jar</packaging>
----

The project adds a `<plugin>` to configure `thorntail-maven-plugin` to
create the runnable `.jar`.

[source,xml]
----
<plugin>
  <groupId>io.thorntail</groupId>
  <artifactId>thorntail-maven-plugin</artifactId>
  <version>${version.thorntail}</version>
  <executions>
    <execution>
      <goals>
        <goal>package</goal>
      </goals>
    </execution>
  </executions>
</plugin>
----

To define the needed parts of Thorntail, dependencies are added

[source,xml]
----
<dependency>
  <groupId>io.thorntail</groupId>
  <artifactId>jaxrs</artifactId>
  <version>${version.thorntail}</version>
</dependency>
----

This dependency provides the JAX-RS APIs.

For the swagger dependency, the `pom.xml` file needs

[source,xml]
----
<dependency>
  <groupId>io.thorntail</groupId>
  <artifactId>swagger</artifactId>
  <version>${project.version}</version>
</dependency>
----

== Swagger Annotations

The JAX-RS API in this example is exposed in the `swagger.json` format
by using the annotations provided by swagger itself. See the swagger wiki
for complete documentation https://github.com/swagger-api/swagger-core/wiki/Annotations-1.5.X.

In our example, we annotate the JAX-RS resource as so:

[source,java]
----
include::src/main/java/org/wildfly/swarm/examples/jaxrs/swagger/TimeResource.java[lines=12..27]
----

See: link:src/main/java/org/wildfly/swarm/examples/jaxrs/swagger/TimeResource.java#L12[TimeResource.java]

By pointing your browser at http://localhost:8080/swagger.json you should see the
API documented similar to this.

[source,json]
----
{
    "swagger":"2.0",
    "info":{"version":"1.0.0"},
    "host":"localhost:8080",
    "basePath":"/swagger",
    "tags":[{"name":"time"}],
    "schemes":["http"],
    "paths": {
        "/time/now": {
            "get": {
                "tags":["time"],
                "summary":"Get the current time",
                "description":"Returns the time as a string",
                "operationId":"get",
                "produces":["application/json"],
                "parameters":[],
                "responses": {
                    "200": {
                        "description":"successful operation",
                        "schema":{"type":"string"}
                    }
                }
            }
        }
    }
}
----

== Run

You can run it many ways:

* mvn package && java -jar ./target/example-jaxrs-swagger-thorntail.jar
* mvn thorntail:run
* From your IDE, run class `org.wildfly.swarm.Swarm`

== Use

To `GET` the JAX-RS resouce

    http://localhost:8080/time/now

To `GET` the API specification as a `swagger.json` document

    http://localhost:8080/swagger.json

== View the API with Swagger-UI

Download the latest Swarm Swagger-UI standalone server jar, for example, 2018.2.0 version:

wget http://repo2.maven.org/maven2/io/thorntail/servers/swagger-ui/2.2.0.Final/swagger-ui-2.2.0.Final-thorntail.jar .

and start it:

java -Dswarm.http.port=8180 -jar swagger-ui-2.2.0.Final-thorntail.jar

Go to 

http://localhost:8180/swagger-ui

and Explore "http://localhost:8080/swagger.json". 


