= JAX-RS &amp; Transactions

This example uses a JAX-RS resource and UserTransaction to start
and end transactions.

> Please raise any issues found with this example in our JIRA:
> https://issues.jboss.org/browse/SWARM[https://issues.jboss.org/browse/SWARM]

== Project `pom.xml`

The project is a normal maven project with `jar` packaging, not `war`.

[source,xml]
----
<packaging>jar</packaging>
----

The project adds a `&lt;plugin&gt;` to configure `wildfly-swarm-plugin` to
create the runnable `.jar`.

[source,xml]
----
<plugin>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>wildfly-swarm-plugin</artifactId>
  <version>${version.wildfly-swarm}</version>
  <configuration>
    <mainClass>org.wildfly.swarm.examples.transactions.Main</mainClass>
  </configuration>
  <executions>
    <execution>
      <goals>
        <goal>package</goal>
      </goals>
    </execution>
  </executions>
</plugin>
----

To define the needed parts of WildFly Swarm, a few dependencies are added

[source,xml]
----
<dependency>
    <groupId>org.wildfly.swarm</groupId>
    <artifactId>jaxrs</artifactId>
    <version>${version.wildfly-swarm}</version>
</dependency>
<dependency>
    <groupId>org.wildfly.swarm</groupId>
    <artifactId>transactions</artifactId>
    <version>${version.wildfly-swarm}</version>
</dependency>
----

== Project `main()`

Since this project deploys JAX-RS resources without a `.war` being constructed,
it provides its own `main()` method (specified above via the `wildfly-swarm-plugin`) to
configure the container and deploy the resources programmatically.

[source]
----
include::src/main/java/org/wildfly/swarm/examples/transactions/Main.java[lines=19..40]
----

This demonstrates starting the container without any deployments,
and then deploying the required classes. 

== Run

* mvn package &amp;&amp; java -jar ./target/example-transactions-shrinkwrap-swarm.jar
* mvn wildfly-swarm:run
* From your IDE, run class `org.wildfly.swarm.examples.transactions.Main`

== Use

[source]
----
http://localhost:8080/
----

The browser will print the message …

[source]
----
Active
----

Then try

[source]
----
http://localhost:8080/begincommit
----

The browser output should be …

[source]
----
Transaction begun ok and committed ok
----

Next

[source]
----
http://localhost:8080/beginrollback
----

And we'll see …

[source]
----
Transaction begun ok and rolled back ok
----

Finally try

[source]
----
http://localhost:8080/nested
----

And you'll see …

[source]
----
Nested transaction support is not enabled!
----

Of course if you've enabled nested transactions in JTA on WildFly then you'll see something different!
