= Resource Adapter via Deployment.

> Please raise any issues found with this example in our JIRA:
> https://issues.jboss.org/browse/THORN

This example demonstrates how to deploy a resource adapter as
a _deployment_.

== Project `pom.xml`

The project is a normal maven project with `jar` packaging, not `war`.

[source,xml]
----
<packaging>jar</packaging>
----

The project adds a `<plugin>` to configure `thorntail-maven-plugin` to
create the runnable `.jar`.  

[source,xml]
----
<plugin>
  <groupId>io.thorntail</groupId>
  <artifactId>thorntail-maven-plugin</artifactId>
  <configuration>
    <mainClass>org.wildfly.swarm.examples.rar.deployment.Main</mainClass>
  </configuration>
  ...
</plugin>
----
    
As with the other examples, this one inherits a few standard executions
from the parent `pom.xml`, particularly the `package` execution.

To define the needed parts of Thorntail, a few dependencies are added.
To support resource adapters in general, the next dependency is required:
    
[source,xml]
----
<dependency>
  <groupId>io.thorntail</groupId>
  <artifactId>resource-adapters</artifactId>
</dependency>
----

Additionally, the RAR archive you wish to deploy is specified as a dependency
within your `pom.xml`

[source,xml]
----
<dependency>
  <groupId>net.java.xadisk</groupId>
  <artifactId>xadisk</artifactId>
  <version>1.2.2</version>
  <type>jar</type>
</dependency>
----

Note, we create the rar archive based on the resource adapter jar.

== Resource Injection

The resource is injected on run-time:

[source,java]
----
include::src/main/java/org/wildfly/swarm/examples/rar/deployment/FileIOBean.java[lines=9..23]
----

See: link:src/main/java/org/wildfly/swarm/examples/rar/deployment/FileIOBean.java#L9[FileIOBean.java]

== Run

You can run it many ways:

* mvn package && java -jar ./target/example-resource-adapter-deployment-thorntail.jar
* mvn thorntail:run
* In your IDE run the `org.wildfly.swarm.examples.rar.deployment.Main` class

== Use

    http://localhost:8080/
