= Datasource via Fraction

> Please raise any issues found with this example in our JIRA:
> https://issues.jboss.org/browse/SWARM

This example demonstrates driver auto-detect functionality.

If a user application includes the appropriate vendor JDBC
library in their normal dependencies, they will be detected
and installed by Thorntail without any additional effort.
An `ExampleDS` also will be auto register if only one verdor's
driver be detected.

== Project `pom.xml`

The project is a normal maven project with `war` packaging,

[source,xml]
----
<packaging>war</packaging>
----

The project adds a `<plugin>` to configure `wildfly-swarm-plugin` to
create the runnable `.jar`. 

[source,xml]
----
<plugin>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>wildfly-swarm-plugin</artifactId>
  ....
</plugin>
----
    
As with the other examples, this one inherits a few standard executions
from the parent `pom.xml`, particularly the `package` execution.
    
To define the needed parts of Thorntail, a few dependencies are added.
The first is not strictly required for configuring datasources, but is
needed for the example to demonstrate usage of the datasource:

[source,xml]
----
<dependency>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>jaxrs</artifactId>
</dependency>
----
    
To support datasources in general, the next dependency is required:
    
[source,xml]
----
<dependency>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>datasources</artifactId>
</dependency>
----

== Run

You can run it many ways:

* mvn package && java -jar ./target/example-datasource-auto-detect-swarm.jar
* mvn wildfly-swarm:run

== Use

    http://localhost:8080/

