INSERT INTO REST_DB_ACCESS("ID", "NAME", "PASSWORD", "ROLE") VALUES (1, 'Penny', 'password', 'admin')
INSERT INTO REST_DB_ACCESS("ID", "NAME", "PASSWORD", "ROLE") VALUES (2, 'Sheldon', 'password', 'user')
INSERT INTO REST_DB_ACCESS("ID", "NAME", "PASSWORD", "ROLE") VALUES (3, 'Amy', 'password', 'guest')
INSERT INTO REST_DB_ACCESS("ID", "NAME", "PASSWORD", "ROLE") VALUES (4, 'Leonard', 'password', 'guest')
INSERT INTO REST_DB_ACCESS("ID", "NAME", "PASSWORD", "ROLE") VALUES (5, 'Bernadette', 'password', 'guest')
INSERT INTO REST_DB_ACCESS("ID", "NAME", "PASSWORD", "ROLE") VALUES (6, 'Raj', 'password', 'guest')
INSERT INTO REST_DB_ACCESS("ID", "NAME", "PASSWORD", "ROLE") VALUES (7, 'Howard', 'password', 'guest')
INSERT INTO REST_DB_ACCESS("ID", "NAME", "PASSWORD", "ROLE") VALUES (8, 'Priya', 'password', 'guest')
